version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node
    working_directory: ~/foia
    steps:
      - checkout
      - type: cache-restore
        key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install dependencies
          command: bundle install --path vendor/bundle
      - type: cache-save
        key: v1-bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - type: cache-restore
        key: v1-node-modules-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - type: cache-save
        key: v1-node-modules-{{ checksum "package.json" }}
        paths:
          - node_modules
      - run:
          name: Prod build
          command: NODE_ENV=prod make build
      - persist_to_workspace:
          root: .
          paths:
            - _site
      - run:
          name: Run tests
          command: make test

  deploy:
    docker:
      - image: circleci/ruby:2.4.1-node
    working_directory: ~/foia
    steps:
      - checkout
      - attach_workspace:
          at: ~/foia
      - run:
          name: Install cf cli
          command: |
            mkdir -p $HOME/bin
            export PATH=$HOME/bin:$PATH
            curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.23.0" | tar xzv -C $HOME/bin
            cf install-plugin autopilot -f -r CF-Community

      - run:
          name: Generate htpasswd
          command: bin/gen_htpasswd.sh _site/.htpasswd
      - deploy:
          name: cf push
          command: |
            export PATH=$HOME/bin:$PATH
            make deploy


workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
